export const products = [
  // Fruits & Vegetables
  {
    name: 'Fresh Bananas',
    description: 'Farm fresh bananas, rich in potassium and natural energy',
    price: 45,
    mrp: 55,
    unit: '1 dozen',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Farm Fresh',
    rating: 4.5,
    reviewCount: 2340,
    dietaryPreference: 'veg',
    tags: ['fruits', 'healthy', 'potassium'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Red Apples',
    description: 'Crisp and juicy red apples from Himachal',
    price: 180,
    mrp: 220,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Himachal Harvest',
    rating: 4.3,
    reviewCount: 1890,
    dietaryPreference: 'veg',
    tags: ['fruits', 'apples', 'healthy'],
    estimatedDeliveryMins: 15
  },
  {
    name: 'Fresh Tomatoes',
    description: 'Locally sourced fresh tomatoes',
    price: 35,
    mrp: 45,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1546470427-227c7369a9b0?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Local Farm',
    rating: 4.2,
    reviewCount: 3200,
    dietaryPreference: 'veg',
    tags: ['vegetables', 'cooking'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Onions',
    description: 'Fresh red onions, essential for every kitchen',
    price: 40,
    mrp: 50,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Farm Fresh',
    rating: 4.4,
    reviewCount: 4500,
    dietaryPreference: 'veg',
    tags: ['vegetables', 'cooking', 'essential'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Potatoes',
    description: 'Fresh potatoes, perfect for all dishes',
    price: 35,
    mrp: 42,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82ber8a7?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Farm Fresh',
    rating: 4.3,
    reviewCount: 5600,
    dietaryPreference: 'veg',
    tags: ['vegetables', 'staple'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Green Capsicum',
    description: 'Fresh green bell peppers',
    price: 60,
    mrp: 75,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400',
    categorySlug: 'fruits-vegetables',
    brand: 'Organic Valley',
    rating: 4.1,
    reviewCount: 890,
    dietaryPreference: 'veg',
    tags: ['vegetables', 'bell pepper'],
    estimatedDeliveryMins: 12
  },

  // Dairy & Breakfast
  {
    name: 'Amul Taaza Milk',
    description: 'Homogenized toned milk, fresh and nutritious',
    price: 27,
    mrp: 28,
    unit: '500 ml',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Amul',
    rating: 4.6,
    reviewCount: 12500,
    dietaryPreference: 'veg',
    tags: ['milk', 'dairy', 'breakfast'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Amul Butter',
    description: 'Pasteurized butter, perfect for bread and cooking',
    price: 56,
    mrp: 58,
    unit: '100 g',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Amul',
    rating: 4.7,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['butter', 'dairy', 'spread'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Brown Eggs',
    description: 'Farm fresh brown eggs, protein rich',
    price: 85,
    mrp: 95,
    unit: '6 pcs',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Farm Fresh',
    rating: 4.4,
    reviewCount: 6700,
    dietaryPreference: 'non_veg',
    tags: ['eggs', 'protein', 'breakfast'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Britannia Bread',
    description: 'Soft and fresh white bread',
    price: 45,
    mrp: 50,
    unit: '400 g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Britannia',
    rating: 4.3,
    reviewCount: 4500,
    dietaryPreference: 'veg',
    tags: ['bread', 'breakfast'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Greek Yogurt',
    description: 'Creamy Greek yogurt, high in protein',
    price: 75,
    mrp: 85,
    unit: '400 g',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Epigamia',
    rating: 4.5,
    reviewCount: 2300,
    dietaryPreference: 'veg',
    tags: ['yogurt', 'protein', 'healthy'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Cheese Slices',
    description: 'Processed cheese slices for sandwiches',
    price: 120,
    mrp: 135,
    unit: '200 g',
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400',
    categorySlug: 'dairy-breakfast',
    brand: 'Amul',
    rating: 4.4,
    reviewCount: 3400,
    dietaryPreference: 'veg',
    tags: ['cheese', 'dairy'],
    estimatedDeliveryMins: 12
  },

  // Snacks & Munchies
  {
    name: 'Lays Classic Salted',
    description: 'Crispy potato chips with classic salt flavor',
    price: 20,
    mrp: 20,
    unit: '52 g',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
    categorySlug: 'snacks-munchies',
    brand: 'Lays',
    rating: 4.5,
    reviewCount: 15600,
    dietaryPreference: 'veg',
    tags: ['chips', 'snacks', 'party'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Kurkure Masala Munch',
    description: 'Crunchy corn puffs with spicy masala',
    price: 20,
    mrp: 20,
    unit: '90 g',
    image: 'https://images.unsplash.com/photo-1613919113640-25732ec5e61f?w=400',
    categorySlug: 'snacks-munchies',
    brand: 'Kurkure',
    rating: 4.4,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['snacks', 'namkeen', 'spicy'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Haldiram Bhujia',
    description: 'Traditional besan bhujia namkeen',
    price: 85,
    mrp: 95,
    unit: '200 g',
    image: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400',
    categorySlug: 'snacks-munchies',
    brand: 'Haldiram',
    rating: 4.6,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['namkeen', 'traditional', 'snacks'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Oreo Cookies',
    description: 'Chocolate sandwich cookies with vanilla cream',
    price: 30,
    mrp: 30,
    unit: '120 g',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=400',
    categorySlug: 'snacks-munchies',
    brand: 'Cadbury',
    rating: 4.7,
    reviewCount: 18700,
    dietaryPreference: 'veg',
    tags: ['cookies', 'chocolate', 'biscuits'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Pringles Original',
    description: 'Stackable potato crisps with original flavor',
    price: 99,
    mrp: 110,
    unit: '107 g',
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=400',
    categorySlug: 'snacks-munchies',
    brand: 'Pringles',
    rating: 4.5,
    reviewCount: 6700,
    dietaryPreference: 'veg',
    tags: ['chips', 'premium', 'snacks'],
    estimatedDeliveryMins: 12
  },

  // Cold Drinks & Juices
  {
    name: 'Coca-Cola',
    description: 'Refreshing cola drink',
    price: 40,
    mrp: 42,
    unit: '750 ml',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
    categorySlug: 'cold-drinks-juices',
    brand: 'Coca-Cola',
    rating: 4.5,
    reviewCount: 23400,
    dietaryPreference: 'veg',
    tags: ['cola', 'soft drink', 'refreshing'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Tropicana Orange Juice',
    description: '100% pure orange juice, no added sugar',
    price: 95,
    mrp: 105,
    unit: '1 L',
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400',
    categorySlug: 'cold-drinks-juices',
    brand: 'Tropicana',
    rating: 4.4,
    reviewCount: 7800,
    dietaryPreference: 'veg',
    tags: ['juice', 'orange', 'healthy'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Red Bull Energy Drink',
    description: 'Energy drink that gives you wings',
    price: 115,
    mrp: 125,
    unit: '250 ml',
    image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=400',
    categorySlug: 'cold-drinks-juices',
    brand: 'Red Bull',
    rating: 4.3,
    reviewCount: 5600,
    dietaryPreference: 'veg',
    tags: ['energy drink', 'caffeine'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Sprite',
    description: 'Clear lemon-lime flavored soft drink',
    price: 40,
    mrp: 42,
    unit: '750 ml',
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400',
    categorySlug: 'cold-drinks-juices',
    brand: 'Sprite',
    rating: 4.4,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['lemon', 'soft drink', 'refreshing'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Real Mango Juice',
    description: 'Mango fruit juice drink',
    price: 85,
    mrp: 95,
    unit: '1 L',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400',
    categorySlug: 'cold-drinks-juices',
    brand: 'Real',
    rating: 4.5,
    reviewCount: 9800,
    dietaryPreference: 'veg',
    tags: ['juice', 'mango', 'fruit'],
    estimatedDeliveryMins: 12
  },

  // Instant & Frozen Food
  {
    name: 'Maggi 2-Minute Noodles',
    description: 'Instant noodles with masala flavor',
    price: 14,
    mrp: 14,
    unit: '70 g',
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400',
    categorySlug: 'instant-frozen',
    brand: 'Maggi',
    rating: 4.6,
    reviewCount: 45600,
    dietaryPreference: 'veg',
    tags: ['noodles', 'instant', 'quick meal'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'McCain French Fries',
    description: 'Crispy frozen french fries',
    price: 150,
    mrp: 175,
    unit: '420 g',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    categorySlug: 'instant-frozen',
    brand: 'McCain',
    rating: 4.4,
    reviewCount: 6700,
    dietaryPreference: 'veg',
    tags: ['frozen', 'fries', 'snacks'],
    estimatedDeliveryMins: 15
  },
  {
    name: 'Cup Noodles',
    description: 'Ready to eat cup noodles',
    price: 50,
    mrp: 55,
    unit: '70 g',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
    categorySlug: 'instant-frozen',
    brand: 'Nissin',
    rating: 4.3,
    reviewCount: 3400,
    dietaryPreference: 'veg',
    tags: ['noodles', 'instant', 'cup'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Frozen Parathas',
    description: 'Ready to cook frozen parathas',
    price: 85,
    mrp: 95,
    unit: '5 pcs',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    categorySlug: 'instant-frozen',
    brand: 'McCain',
    rating: 4.2,
    reviewCount: 2300,
    dietaryPreference: 'veg',
    tags: ['frozen', 'paratha', 'breakfast'],
    estimatedDeliveryMins: 15
  },
  {
    name: 'Frozen Momos',
    description: 'Vegetable momos ready to steam',
    price: 120,
    mrp: 140,
    unit: '10 pcs',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400',
    categorySlug: 'instant-frozen',
    brand: 'Prasuma',
    rating: 4.3,
    reviewCount: 4500,
    dietaryPreference: 'veg',
    tags: ['frozen', 'momos', 'snacks'],
    estimatedDeliveryMins: 15
  },

  // Atta, Rice & Dal
  {
    name: 'Aashirvaad Atta',
    description: 'Whole wheat flour for soft rotis',
    price: 280,
    mrp: 310,
    unit: '5 kg',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    categorySlug: 'atta-rice-dal',
    brand: 'Aashirvaad',
    rating: 4.7,
    reviewCount: 34500,
    dietaryPreference: 'veg',
    tags: ['atta', 'flour', 'staple'],
    estimatedDeliveryMins: 15
  },
  {
    name: 'India Gate Basmati Rice',
    description: 'Premium aged basmati rice',
    price: 450,
    mrp: 520,
    unit: '5 kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    categorySlug: 'atta-rice-dal',
    brand: 'India Gate',
    rating: 4.6,
    reviewCount: 23400,
    dietaryPreference: 'veg',
    tags: ['rice', 'basmati', 'premium'],
    estimatedDeliveryMins: 15
  },
  {
    name: 'Toor Dal',
    description: 'Split pigeon peas, essential for dal',
    price: 160,
    mrp: 180,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1585996746505-d1c4c9a2e6e0?w=400',
    categorySlug: 'atta-rice-dal',
    brand: 'Tata Sampann',
    rating: 4.4,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['dal', 'pulses', 'protein'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Moong Dal',
    description: 'Yellow moong dal, easy to digest',
    price: 140,
    mrp: 160,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1613743990305-b0a7c8e5d7e1?w=400',
    categorySlug: 'atta-rice-dal',
    brand: 'Tata Sampann',
    rating: 4.5,
    reviewCount: 6700,
    dietaryPreference: 'veg',
    tags: ['dal', 'pulses', 'healthy'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Poha',
    description: 'Flattened rice for breakfast',
    price: 55,
    mrp: 65,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    categorySlug: 'atta-rice-dal',
    brand: 'Local',
    rating: 4.3,
    reviewCount: 3400,
    dietaryPreference: 'veg',
    tags: ['poha', 'breakfast', 'light'],
    estimatedDeliveryMins: 10
  },

  // Tea, Coffee & Health Drinks
  {
    name: 'Tata Tea Gold',
    description: 'Premium tea with 15% long leaves',
    price: 195,
    mrp: 220,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    categorySlug: 'tea-coffee',
    brand: 'Tata Tea',
    rating: 4.5,
    reviewCount: 18900,
    dietaryPreference: 'veg',
    tags: ['tea', 'premium', 'chai'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Nescafe Classic',
    description: 'Instant coffee for a quick brew',
    price: 350,
    mrp: 395,
    unit: '200 g',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    categorySlug: 'tea-coffee',
    brand: 'Nescafe',
    rating: 4.6,
    reviewCount: 23400,
    dietaryPreference: 'veg',
    tags: ['coffee', 'instant', 'caffeine'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Bournvita',
    description: 'Chocolate health drink for kids',
    price: 240,
    mrp: 275,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?w=400',
    categorySlug: 'tea-coffee',
    brand: 'Cadbury',
    rating: 4.5,
    reviewCount: 15600,
    dietaryPreference: 'veg',
    tags: ['health drink', 'chocolate', 'kids'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Green Tea',
    description: 'Natural green tea for wellness',
    price: 180,
    mrp: 210,
    unit: '100 bags',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400',
    categorySlug: 'tea-coffee',
    brand: 'Lipton',
    rating: 4.3,
    reviewCount: 7800,
    dietaryPreference: 'veg',
    tags: ['green tea', 'healthy', 'wellness'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Horlicks',
    description: 'Health and nutrition drink',
    price: 320,
    mrp: 365,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=400',
    categorySlug: 'tea-coffee',
    brand: 'Horlicks',
    rating: 4.4,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['health drink', 'nutrition'],
    estimatedDeliveryMins: 12
  },

  // Masala, Oil & More
  {
    name: 'Fortune Sunflower Oil',
    description: 'Refined sunflower oil for healthy cooking',
    price: 180,
    mrp: 200,
    unit: '1 L',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    categorySlug: 'masala-oil',
    brand: 'Fortune',
    rating: 4.5,
    reviewCount: 18900,
    dietaryPreference: 'veg',
    tags: ['oil', 'cooking', 'healthy'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'MDH Garam Masala',
    description: 'Blend of aromatic spices',
    price: 95,
    mrp: 110,
    unit: '100 g',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400',
    categorySlug: 'masala-oil',
    brand: 'MDH',
    rating: 4.6,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['masala', 'spices', 'cooking'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Turmeric Powder',
    description: 'Pure turmeric powder for cooking',
    price: 65,
    mrp: 75,
    unit: '200 g',
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400',
    categorySlug: 'masala-oil',
    brand: 'Everest',
    rating: 4.4,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['turmeric', 'spices', 'healthy'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Red Chilli Powder',
    description: 'Hot and spicy red chilli powder',
    price: 85,
    mrp: 95,
    unit: '200 g',
    image: 'https://images.unsplash.com/photo-1599909533681-74a182569c84?w=400',
    categorySlug: 'masala-oil',
    brand: 'Everest',
    rating: 4.3,
    reviewCount: 6700,
    dietaryPreference: 'veg',
    tags: ['chilli', 'spices', 'hot'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Saffola Gold Oil',
    description: 'Blended edible vegetable oil',
    price: 210,
    mrp: 240,
    unit: '1 L',
    image: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400',
    categorySlug: 'masala-oil',
    brand: 'Saffola',
    rating: 4.5,
    reviewCount: 9800,
    dietaryPreference: 'veg',
    tags: ['oil', 'healthy', 'heart'],
    estimatedDeliveryMins: 12
  },

  // Sweet Tooth
  {
    name: 'Dairy Milk Silk',
    description: 'Smooth and creamy milk chocolate',
    price: 85,
    mrp: 90,
    unit: '60 g',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400',
    categorySlug: 'sweet-tooth',
    brand: 'Cadbury',
    rating: 4.8,
    reviewCount: 34500,
    dietaryPreference: 'veg',
    tags: ['chocolate', 'premium', 'gift'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'KitKat',
    description: 'Crispy wafer fingers covered in chocolate',
    price: 40,
    mrp: 42,
    unit: '37.3 g',
    image: 'https://images.unsplash.com/photo-1582176604856-e824b4736522?w=400',
    categorySlug: 'sweet-tooth',
    brand: 'Nestle',
    rating: 4.6,
    reviewCount: 23400,
    dietaryPreference: 'veg',
    tags: ['chocolate', 'wafer', 'snack'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Gulab Jamun',
    description: 'Traditional Indian sweet',
    price: 120,
    mrp: 140,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1666190050371-db0a2b6f4e6e?w=400',
    categorySlug: 'sweet-tooth',
    brand: 'Haldiram',
    rating: 4.5,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['sweets', 'indian', 'traditional'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Rasgulla',
    description: 'Soft spongy cottage cheese balls in syrup',
    price: 110,
    mrp: 130,
    unit: '500 g',
    image: 'https://images.unsplash.com/photo-1601303516403-e2d1b7a7e8b0?w=400',
    categorySlug: 'sweet-tooth',
    brand: 'Haldiram',
    rating: 4.4,
    reviewCount: 6700,
    dietaryPreference: 'veg',
    tags: ['sweets', 'bengali', 'traditional'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Ferrero Rocher',
    description: 'Premium hazelnut chocolate',
    price: 450,
    mrp: 499,
    unit: '16 pcs',
    image: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400',
    categorySlug: 'sweet-tooth',
    brand: 'Ferrero',
    rating: 4.8,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['chocolate', 'premium', 'gift'],
    estimatedDeliveryMins: 12
  },

  // Personal Care
  {
    name: 'Dettol Handwash',
    description: 'Antibacterial liquid handwash',
    price: 99,
    mrp: 115,
    unit: '200 ml',
    image: 'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400',
    categorySlug: 'personal-care',
    brand: 'Dettol',
    rating: 4.5,
    reviewCount: 15600,
    dietaryPreference: 'veg',
    tags: ['hygiene', 'handwash', 'antibacterial'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Colgate Toothpaste',
    description: 'Cavity protection toothpaste',
    price: 95,
    mrp: 105,
    unit: '150 g',
    image: 'https://images.unsplash.com/photo-1559650656-5d1d361ad10e?w=400',
    categorySlug: 'personal-care',
    brand: 'Colgate',
    rating: 4.6,
    reviewCount: 23400,
    dietaryPreference: 'veg',
    tags: ['dental', 'toothpaste', 'oral care'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Head & Shoulders Shampoo',
    description: 'Anti-dandruff shampoo',
    price: 180,
    mrp: 210,
    unit: '180 ml',
    image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400',
    categorySlug: 'personal-care',
    brand: 'Head & Shoulders',
    rating: 4.4,
    reviewCount: 12300,
    dietaryPreference: 'veg',
    tags: ['shampoo', 'hair care', 'dandruff'],
    estimatedDeliveryMins: 12
  },
  {
    name: 'Dove Soap',
    description: 'Moisturizing beauty bar',
    price: 55,
    mrp: 62,
    unit: '100 g',
    image: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f214?w=400',
    categorySlug: 'personal-care',
    brand: 'Dove',
    rating: 4.5,
    reviewCount: 18900,
    dietaryPreference: 'veg',
    tags: ['soap', 'moisturizing', 'skin care'],
    estimatedDeliveryMins: 10
  },
  {
    name: 'Nivea Body Lotion',
    description: 'Nourishing body lotion for soft skin',
    price: 220,
    mrp: 250,
    unit: '200 ml',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
    categorySlug: 'personal-care',
    brand: 'Nivea',
    rating: 4.4,
    reviewCount: 8900,
    dietaryPreference: 'veg',
    tags: ['lotion', 'skin care', 'moisturizer'],
    estimatedDeliveryMins: 12
  }
];
